name: Update Readme

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

permissions: write-all

jobs:
  update:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: run
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
