name: Update Readme

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

permissions: read-all|write-all

jobs:
  update:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: run
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: commit
        run: |
          git config --local user.name "hugo-stars bot"
          git commit -m "Updated ranking" -a
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
